### ISSUE TITLE
Add support for PHP8

### ISSUE THREAD

**Issue by ferrastas** [beechit/json-to-code-climate-subset-converter#35]
Seems a smooth transition, except for https://github.com/thecodingmachine/safe that it's not compatible and we will need to use https://github.com/thecodingmachine/safe8

**Comment by ttomdewit** [comment]
It dropped PHP 7 support entirely, I'm not sure how to tackle that and support both 7.3, 7.4 and 8. I'll try and do some research and see how we can tackle this.

**Comment by ttomdewit** [comment]
One option that I see is create a 2.x branch and support PHP8 from there. Others will still be able to use the 1.x branch for PHP 7.x support.

**Comment by ttomdewit** [comment]
Closed via #39
